### ISSUE TITLE
Caching Mechanism for choosing skip branch

### ISSUE THREAD

**Issue by Kyuseok-nam** [horseee/DeepCache#39]
Hi, I was going over the code for DeepCache and was quite confused with a particular part of the code where you choose the skip branch in the unet model. 

from unet_2d_condition.py file, line 1102~1108, Why did you implment this if condition? it seems to limit access of other skip branch or layers.

Also if I'm understanding correctly,
Cache_layer_id : indicates which big block to choose from ex) CrossAttn2Dblock, DownBlock2D,...
Cache_block_id:  indicates which block (small blocks inside the big block) to choose from ex) transformer2dmodel, resnet

is this correct?  

![스크린샷 2024-04-23 172624](https://github.com/horseee/DeepCache/assets/84071888/1825a3e2-bb51-4a32-9e99-85694f9c40c7)

**Comment by horseee** [comment]
Hi, it's because of the mismatch of the down block and the up block. 

The cache_block_id/cache_layer_id we use here is used in the downsampling block/layer. However,  the downsampling block and upsampling block that are connected by the skip branch didn't share the same layer_id/block_id. Thus, this part of code functions like a layer/block mapping, and the goal is to find the corresponding layer/block id for this skip branch in the upsampling process
